- project:
    templates:
      - openstack-python3-xena-jobs-ironic-bugfix
      - publish-openstack-docs-pti
      - check-requirements
    check:
      jobs:
        - openstack-tox-functional:
            nodeset: ubuntu-focal
            required-projects:
                - name: openstack/requirements
                  override-checkout: stable/xena
        - openstack-tox-cover:
            nodeset: ubuntu-focal
            required-projects:
                - name: openstack/requirements
                  override-checkout: stable/xena
        - ipa-tox-examples
        # NOTE(iurygregory) Only run this two jobs since we are testing
        # wholedisk + partition on tempest
        - ipa-tempest-bios-ipmi-direct-src
        - ipa-tempest-uefi-redfish-vmedia-src:
            voting: false
            # NOTE(TheJulia) Disabling voting for redfish due to issues
            # running swift tests. There *is* no override for non-swift
            # in much older versions.
        - ironic-standalone-ipa-src
        - metalsmith-integration-ipa-src
        - metalsmith-integration-ipa-src-uefi:
            voting: false
        # NOTE(dtantsur): non-voting because IPA source code is very unlikely
        # to break them. They rather serve as a canary for broken POST jobs.
        - ironic-python-agent-check-image-tinyipa:
            voting: false
        - ironic-python-agent-check-image-dib-centos8:
            voting: false
        # Non-voting jobs
        - ipa-tempest-ironic-inspector-src:
            voting: false
        - ipa-tox-bandit:
            voting: false
    gate:
      jobs:
        - openstack-tox-functional:
            nodeset: ubuntu-focal
            required-projects:
                - name: openstack/requirements
                  override-checkout: stable/xena
        - openstack-tox-cover:
            nodeset: ubuntu-focal
            required-projects:
                - name: openstack/requirements
                  override-checkout: stable/xena
        - ipa-tempest-bios-ipmi-direct-src
        # - ipa-tempest-uefi-redfish-vmedia-src
        # NOTE(TheJulia): Disabling for now, since
        # we don't support non-swift on this branch.
        - metalsmith-integration-ipa-src
        - ironic-standalone-ipa-src
    post:
      jobs:
        - ironic-python-agent-build-image-tinyipa
        - ironic-python-agent-build-image-dib-centos8
